### ISSUE TITLE
RuntimeError: invalid device ordinal

### ISSUE THREAD

**Issue by sanzimu** [danpovey/fast_rnnt#15]
I ran the fast_rnnt.get_rnnt_prune_ranges() function with a RuntimeError: Invalid device ordinal .
Here are the error details.
ranges = self.fast_rnnt.get_rnnt_prune_ranges(
  File "/opt/conda/lib/python3.8/site-packages/fast_rnnt-1.0-py3.8-linux-x86_64.egg/fast_rnnt/rnnt_loss.py", line 580, in get_rnnt_prune_ranges
    s_begin = _adjust_pruning_lower_bound(s_begin, 2 if T1 == T else s_range)
  File "/opt/conda/lib/python3.8/site-packages/fast_rnnt-1.0-py3.8-linux-x86_64.egg/fast_rnnt/rnnt_loss.py", line 466, in _adjust_pruning_lower_bound
    fast_rnnt.monotonic_lower_bound_(s_begin)
RuntimeError: invalid device ordinal

**Comment by pkufool** [comment]
How do you run it with fast_rnnt? Can you show your running command? Looks like to me, it is the wrong configuration of CUDA devices.

**Comment by sanzimu** [comment]
> How do you run it with fast_rnnt? Can you show your running command? Looks like to me, it is the wrong configuration of CUDA devices.

For data security reasons, we can't show the code here, but only part of it.

export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7,8"

class E2E():
    def forward(self, feats, feats_len, target, target_len):
         target = target.to(torch.int64)                                                                                                                                                            
         am = self.lin_enc_out(encoder_out)                                                                                                                                                              
         lm = self.lin_dec_out(decoder_out)                                                                                                                                                                                                                                                                                              
         boundary = torch.zeros((lm.size(0), 4), dtype=torch.int64, device=am.device)                                                                                                               
         boundary[:, 2] = target_len                                                                                                                                                                
         boundary[:, 3] = encoder_out_len                                                                                                                                                                  
         simple_loss, (px_grad, py_grad) = self.fast_rnnt.rnnt_loss_smoothed(                                                                                                                       
             lm=lm.float(),                                                                                                                                                                         
             am=am.float(),                                                                                                                                                                         
             symbols=target,                                                                                                                                                                        
             termination_symbol=self.blank_id,                                                                                                                                                      
             lm_only_scale=0.25,                                                                                                                                                                    
             am_only_scale=0.0,                                                                                                                                                                     
             boundary=boundary,                                                                                                                                                                     
             reduction="sum",                                                                                                                                                                       
             return_grad=True,                                                                                                                                                                      
          )                                                                                                                                                                                          
                                                    
          ranges = self.fast_rnnt.get_rnnt_prune_ranges(                                                                                                                                             
                              px_grad=px_grad,                                                                                                                                                                       
                              py_grad=py_grad,                                                                                                                                                                       
                              boundary=boundary,                                                                                                                                                                     
                              s_range=2,                                                                                                                                                                             
                         ) 
                                                                                                                                                                                         
          am_pruned, lm_pruned = self.fast_rnnt.do_rnnt_pruning(                                                                                                                                     
                                                        am=self.joint_network.lin_enc(encoder_out),                                                                                                                                                 
                                                        lm=self.joint_network.lin_dec(decoder_out),                                                                                                                                               
                                                        ranges=ranges,                                                                                                                                                                         
                                                     )     
                                                                                                                                                                                      
          logits = self.joint_network(am_pruned, lm_pruned)                                                                                                                                          
          pruned_loss = self.fast_rnnt.rnnt_loss_pruned(                                                                                                                                             
                                      logits=logits.float(),                                                                                                                                                                 
                                      symbols=target,                                                                                                                                                                        
                                      termination_symbol=self.blank_id,                                                                                                                                                      
                                      boundary=boundary,                                                                                                                                                                     
                                      reduction="sum",                                                                                                                                                                       
                                  )
def main():
    rank = args.rank 
    local_rank=args.gpu_id
    torch.distributed.init_process_group(backend="nccl", init_method=init_method,  world_size=args.world_size, rank=rank)
    torch.cuda.set_device(local_rank)
    device = torch.device("cuda",local_rank)
    model=E2E()
    model.to(device) 
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[local_rank])
    model(feats, feats_len, target, target_len)

if __name__ == '__main__':
    main()

**Comment by pkufool** [comment]
> For data security reasons, i can't show the code here, but only part of it.
Thanks！I see. 

> export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7,8"
BTW, do you have 9 cards in your machine?  What's the world_size?

**Comment by csukuangfj** [comment]
Are you using the same machine to compile and run fast_rnnt?

**Comment by sanzimu** [comment]
> > For data security reasons, i can't show the code here, but only part of it.
> 
> Thanks！I see.
> 
> > export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7,8"
> 
> BTW, do you have 9 cards in your machine? What's the world_size?
sorry，it's only 8 cards. I made a mistake here, but my train script is "export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7""

**Comment by sanzimu** [comment]
> Are you using the same machine to compile and run fast_rnnt?

yes

**Comment by pkufool** [comment]
Can you run your training with torch.rnnt_loss successfully? Seems that it gets wrong device id somewhere, I checked the code and did not see obvious bugs in the function listed in the backtrace.

**Comment by pkufool** [comment]
Does this error raise at the begining or at the middle of your training?

**Comment by sanzimu** [comment]
> Can you run your training with torch.rnnt_loss successfully? Seems that it gets wrong device id somewhere, I checked the code and did not see obvious bugs in the function listed in the backtrace.

It can run warp-transducer loss successfully

**Comment by sanzimu** [comment]
> Does this error raise at the begining or at the middle of your training?

The Error happend at the begining of the training

**Comment by sanzimu** [comment]
ngpu=8
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
for ((i=0; i<$ngpu; i++)); do
 (
gpu_id=$(echo $CUDA_VISIBLE_DEVICES | cut -d',' -f$[$i+1])
 98                 rank=`expr $node_rank \* $ngpu + $i`
 99                 python ./src/am_train_recog.py --node-num $node_num \
100                         --config $conf \
101                         --seed $seed \
102                         --mode train \
103                         --ngpu $ngpu \
104                         --gpu-id $gpu_id \
105                         --train-data $train_data \
106                         --split-data-part $split_data_part \
107                         --output-dir $output_dir \
108                         --verbose $verbose \
109                         --preprocess-conf $preprocess_conf \
110                         --pre-model $pre_model \
111                         --world-size $world_size \
112                         --rank $rank \
113                         $opt
114         ) &
115     done
116     wait

**Comment by csukuangfj** [comment]
Is there a similar issue if you use the pruned rnnt loss from k2?

**Comment by csukuangfj** [comment]
Also, does it happen if you use a single GPU or fewer GPUs for training?

**Comment by sanzimu** [comment]
> Also, does it happen if you use a single GPU or fewer GPUs for training?

Same error happened when using 1 or 4 GPU

**Comment by sanzimu** [comment]
> Is there a similar issue if you use the pruned rnnt loss from k2?

I'll try it .  Intalling  runtime env is  annoying ~~~

**Comment by sanzimu** [comment]
Hmm, i  can run fast_rnnt successfully with cuda-10.1. but failed with 11.2. And i trace the error happend in https://github.com/danpovey/fast_rnnt/blob/master/fast_rnnt/csrc/utils.cu#:~:text=auto%20s%20%3D%20cub%3A%3ADeviceScan%3A%3AInclusiveScan(nullptr%2C%20temp_storage_bytes%2C

**Comment by csukuangfj** [comment]
> And i trace the error happend in

Are there error logs and backtraces?

**Comment by sanzimu** [comment]
> > And i trace the error happend in
> 
> Are there error logs and backtraces?

No;I print the return error log by cub::DeviceScan::InclusiveScan, error code show 101(invalid device ordinal)

**Comment by sanzimu** [comment]
I have sovled this porblem using cuda-10.1
