### ISSUE TITLE
ModuleNotFoundError: No module named '_fast_rnnt'

### ISSUE THREAD

**Issue by Tan-ht** [danpovey/fast_rnnt#17]
I installed this module successfully with pip, while this error occurred when I tried to import the fast_rnnt.
![1661827816572](https://user-images.githubusercontent.com/82324996/187337745-ff7560ac-6497-4c5c-bdac-23da2630d582.jpg)
![1661827868892](https://user-images.githubusercontent.com/82324996/187337832-cccf5bea-b39d-4a8f-825b-56c4b6f3675d.jpg)

**Comment by csukuangfj** [comment]
> I installed this module successfully with pip

Could you post the installation logs?

**Comment by csukuangfj** [comment]
I see that you are using Windows. Unfortunately, the current build system does not handle Windows correctly.

I will make a PR.
