### ISSUE TITLE
An error occurred while compiling the source code

### ISSUE THREAD

**Issue by jiay7** [danpovey/fast_rnnt#6]
Thank you for the fast_rnnt, I got the error (show blow) when I run "python setup.py install".
![1655099928(1)](https://user-images.githubusercontent.com/74249633/173289203-22816d59-73e1-47d4-ab3a-f999b1cec06a.png)

python=3.8.11 torch verison=1.10.1 cudatoolkit=10.2.89 CUDA version=10.2.  GCC version =5.3.1. cmake version=3.23.0

Is this known issue? How can it be debugged and solved?

Thank you!

**Comment by csukuangfj** [comment]
It requires a version of GCC that supports C++14. 

From https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2014, GCC >= 6.1 supports C++14.
Your GCC version 5.3 is too low. Please try a newer one, e.g., GCC 7.5

---

Note: You can also try to install k2: https://k2-fsa.github.io/k2/installation/index.html , which also contains pruned RNN-T.
You can find its usage in https://github.com/k2-fsa/icefall

**Comment by jiay7** [comment]
Thank you for your reply. I used gcc==7.5, which works.
