### ISSUE TITLE
#error -- unsupported GUN version ! gcc version later than 5.3 are not supported!

### ISSUE THREAD

**Issue by Butterfly-c** [danpovey/fast_rnnt#9]
I ran into the following problems，when i run the setup.py:

/opt/lib/cuda-8.0/bin/..//include/host_config.h:115:2 #error -- unsupported GUN version ! gcc version later than 5.3 are not supported!

the environment is :
gcc 5.4.0 
pytorch 1.7.1
cuda-10.2
python 3.7
 (There are several different versions of cuda in the environment.)

when I set the following configs in CMakeList.txt, I still get the same error

set(CUDA_TOOLKIT_ROOT_DIR /opt/lib/cuda-10.2)
set(CMAKE_C_COMPILER /usr/bin/gcc) (gcc -v 4.8.5)
set(CMAKE_CXX_COMPILER /usr/bin/++)

**Comment by pkufool** [comment]
Try setting cuda-10.2 as follows：
```
export CUDA_HOME=/opt/lib/cuda-10.2
export PATH=$CUDA_HOME/bin:$PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

export CUDA_TOOLKIT_ROOT_DIR=$CUDA_HOME
export CUDA_TOOLKIT_ROOT=$CUDA_HOME
export CUDA_BIN_PATH=$CUDA_HOME
export CUDA_PATH=$CUDA_HOME
export CUDA_INC_PATH=$CUDA_HOME/targets/x86_64-linux
```
And the fast_rnnt requires the c++14 standard, you might need to use a newer gcc version.

**Comment by Butterfly-c** [comment]
> 
Thanks! The environment is compiled successfully.
